import type { Metadata } from 'next'
import { ColorSchemeScript, MantineProvider } from '@mantine/core'
import '@mantine/core/styles.css'
import Header from '@/components/Header/Header'
import './globals.css'
import '@/styles/reset.scss'
import Footer from '@/components/Footer/Footer'

export const metadata: Metadata = {
  title: 'Bloom Technical Test',
  description: 'Generated by create next app'
}

const navigationItems = [
  { link: '/', label: 'Je recrute !' },
  { link: '/search', label: "Offres d'emploi" },
  { link: '/', label: 'Mes offres', icon: true },
  { link: '/', label: 'Se connecter', button: true }
]

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <head>
        <ColorSchemeScript />
      </head>
      <body>
        <MantineProvider>
          <Header navItems={navigationItems} />
          {children}
          <Footer />
        </MantineProvider>
      </body>
    </html>
  )
}
